# Generated by Django 5.2.3 on 2025-08-14 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0014_merge_likability_slider_single_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringconfiguration',
            name='points_per_referral',
            field=models.IntegerField(default=5, help_text='Points awarded per patient referral (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='referrer_score_weight',
            field=models.IntegerField(default=25, help_text='Weight for referrer score behavior (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
