# Generated by Django 5.2.3 on 2025-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0016_remove_unlikability_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('clinic_location', models.CharField(blank=True, max_length=200)),
                ('clinic_timezone', models.CharField(default='Australia/Sydney', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RatedApp System Settings',
                'verbose_name_plural': 'RatedApp System Settings',
            },
        ),
    ]
