# Generated by Django 5.2.3 on 2025-07-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0006_scoringconfiguration_points_per_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringconfiguration',
            name='points_per_consecutive_attendance',
            field=models.IntegerField(default=2, help_text='Points awarded per consecutive attendance (1-10)'),
        ),
    ]
