# Generated by Django 5.2.3 on 2025-09-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0016_remove_unlikability_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=200, verbose_name='Clinic Name')),
                ('clinic_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinic Location')),
                ('clinic_timezone', models.CharField(choices=[('Australia/Sydney', 'Sydney'), ('Australia/Melbourne', 'Melbourne'), ('Australia/Brisbane', 'Brisbane'), ('Australia/Perth', 'Perth'), ('Australia/Adelaide', 'Adelaide'), ('Australia/Darwin', 'Darwin'), ('Australia/Hobart', 'Hobart'), ('Australia/Canberra', 'Canberra')], default='Australia/Sydney', max_length=100, verbose_name='Clinic Timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RatedApp Clinic Settings',
                'verbose_name_plural': 'RatedApp Clinic Settings',
            },
        ),
    ]
