# Generated by Django 5.2.3 on 2025-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0018_make_clinic_location_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorcategory',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='behaviorcategory',
            name='software_integration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Software Integration'),
        ),
    ]
