# Generated by Django 5.2.3 on 2025-09-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0017_ratedappsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatedAppSettings',
        ),
    ]
