# Generated by Django 5.2.3 on 2025-08-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0012_allow_zero_points_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='points_per_cancellation',
            field=models.IntegerField(default=3, help_text='Points deducted per cancellation (1-10)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='points_per_consecutive_attendance',
            field=models.IntegerField(default=2, help_text='Points awarded per consecutive attendance (1-10)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='points_per_dna',
            field=models.IntegerField(default=5, help_text='Points deducted per DNA (1-10)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='points_per_unpaid_invoice',
            field=models.IntegerField(default=10, help_text='Points deducted per unpaid invoice (1-100)'),
        ),
    ]
