# Generated by Django 5.2.3 on 2025-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0009_add_points_per_dna'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringconfiguration',
            name='points_per_unpaid_invoice',
            field=models.IntegerField(default=10, help_text='Points deducted per unpaid invoice (1-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='age_demographics_weight',
            field=models.IntegerField(default=10, help_text='Weight for target age demographic (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='cancellations_weight',
            field=models.IntegerField(default=20, help_text='Penalty weight per cancellation (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='consecutive_attendance_weight',
            field=models.IntegerField(default=30, help_text='Weight for attendance streak (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='dna_weight',
            field=models.IntegerField(default=50, help_text='Penalty weight per DNA (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='future_appointments_weight',
            field=models.IntegerField(default=20, help_text='Weight for future appointments (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Currently active configuration'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='likability_weight',
            field=models.IntegerField(default=20, help_text='Weight for manual likability (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='open_dna_invoice_weight',
            field=models.IntegerField(default=100, help_text='Penalty weight for open DNA invoice (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='unlikability_weight',
            field=models.IntegerField(default=20, help_text='Weight for manual unlikability (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='unpaid_invoices_weight',
            field=models.IntegerField(default=50, help_text='Penalty weight per unpaid invoice (0-100)'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='yearly_spend_weight',
            field=models.IntegerField(default=25, help_text='Weight for yearly spend (0-100)'),
        ),
    ]
