# Generated by Django 5.2.3 on 2025-07-17 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0010_add_points_per_unpaid_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_spend', models.DecimalField(decimal_places=2, help_text='Minimum spend amount', max_digits=10)),
                ('max_spend', models.DecimalField(decimal_places=2, help_text='Maximum spend amount (999999.99 for unlimited)', max_digits=10)),
                ('percentage', models.IntegerField(help_text='Percentage of slider value', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_brackets', to='patient_rating.scoringconfiguration')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('config', 'order')},
            },
        ),
    ]
