# Generated by Django 5.2.3 on 2025-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0003_scoringconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='age_demographics_weight',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='cancellations_weight',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='consecutive_attendance_weight',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='dna_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='future_appointments_weight',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='likability_weight',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='open_dna_invoice_weight',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='unlikability_weight',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='unpaid_invoices_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='yearly_spend_weight',
            field=models.IntegerField(default=25),
        ),
    ]
