# Generated by Django 5.2.3 on 2025-08-28 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_appointments_weight', models.FloatField(default=20)),
                ('age_demographics_weight', models.FloatField(default=15)),
                ('yearly_spend_weight', models.FloatField(default=25)),
                ('consecutive_attendance_weight', models.FloatField(default=20)),
                ('referrer_score_weight', models.FloatField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
