# Generated by Django 5.2.3 on 2025-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0002_alter_behaviorcategory_scoring_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('future_appointments_weight', models.IntegerField(default=20, help_text='Weight for future appointments (0-100)')),
                ('age_demographics_weight', models.IntegerField(default=10, help_text='Weight for target age demographic (0-100)')),
                ('yearly_spend_weight', models.IntegerField(default=25, help_text='Weight for yearly spend (0-100)')),
                ('consecutive_attendance_weight', models.IntegerField(default=30, help_text='Weight for attendance streak (0-100)')),
                ('likability_weight', models.IntegerField(default=20, help_text='Weight for manual likability (0-100)')),
                ('cancellations_weight', models.IntegerField(default=20, help_text='Penalty weight per cancellation (0-100)')),
                ('dna_weight', models.IntegerField(default=50, help_text='Penalty weight per DNA (0-100)')),
                ('unpaid_invoices_weight', models.IntegerField(default=50, help_text='Penalty weight per unpaid invoice (0-100)')),
                ('open_dna_invoice_weight', models.IntegerField(default=100, help_text='Penalty weight for open DNA invoice (0-100)')),
                ('unlikability_weight', models.IntegerField(default=20, help_text='Weight for manual unlikability (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently active configuration')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
