# Generated by Django 5.2.3 on 2025-06-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorcategory',
            name='scoring_method',
            field=models.CharField(choices=[('boolean', 'True/False'), ('bracket', 'Bracket-based'), ('incremental', 'Accumulative'), ('strike', 'Strike System'), ('manual_input', 'Manual Input (0-100)')], max_length=20),
        ),
    ]
