# Generated by Django 5.2.3 on 2025-07-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0005_agebracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringconfiguration',
            name='points_per_cancellation',
            field=models.IntegerField(default=3, help_text='Points deducted per cancellation (1-10)'),
        ),
    ]
