# Generated by Django 5.2.3 on 2025-07-08 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0004_alter_scoringconfiguration_age_demographics_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('percentage', models.IntegerField(help_text='Percentage of slider maximum (0-100)')),
                ('order', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_brackets', to='patient_rating.scoringconfiguration')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('config', 'order')},
            },
        ),
    ]
