# Generated by Django 5.2.3 on 2025-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0008_patient_likability_patient_unlikability'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringconfiguration',
            name='points_per_dna',
            field=models.IntegerField(default=5, help_text='Points deducted per DNA (1-10)'),
        ),
    ]
