# Generated by Django 5.2.3 on 2025-06-26 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('behavior_type', models.CharField(choices=[('positive', 'Positive Behavior'), ('negative', 'Negative Behavior')], max_length=10)),
                ('scoring_method', models.CharField(choices=[('boolean', 'True/False'), ('bracket', 'Bracket-based'), ('incremental', 'Accumulative'), ('strike', 'Strike System')], max_length=20)),
                ('max_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliniko_patient_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('total_score', models.IntegerField(default=0)),
                ('calculated_rating', models.CharField(blank=True, max_length=1)),
                ('override_active', models.BooleanField(default=False)),
                ('override_rating', models.CharField(blank=True, max_length=1)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_rating', models.CharField(max_length=1)),
                ('override_rating', models.CharField(max_length=1)),
                ('admin_user', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('override_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='patient_rating.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointments_booked', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('yearly_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referrals_made', models.PositiveIntegerField(default=0)),
                ('consecutive_attendance_count', models.PositiveIntegerField(default=0)),
                ('no_appointments_booked', models.BooleanField(default=False)),
                ('dna_count', models.PositiveIntegerField(default=0)),
                ('cancellation_count', models.PositiveIntegerField(default=0)),
                ('has_unpaid_cancellation_fee', models.BooleanField(default=False)),
                ('unpaid_invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='patient_rating.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bracket_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_awarded', models.IntegerField()),
                ('bracket_order', models.PositiveIntegerField(default=0)),
                ('behavior_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='patient_rating.behaviorcategory')),
            ],
            options={
                'ordering': ['bracket_order'],
            },
        ),
        migrations.CreateModel(
            name='PatientBehaviorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data_value', models.TextField()),
                ('calculated_points', models.IntegerField()),
                ('max_possible_points', models.IntegerField()),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('behavior_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_rating.behaviorcategory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_scores', to='patient_rating.patient')),
            ],
            options={
                'unique_together': {('patient', 'behavior_category')},
            },
        ),
    ]
