# Generated by Django 5.2.3 on 2025-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0017_ratedappsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedappsettings',
            name='clinic_location',
            field=models.CharField(max_length=200, verbose_name='Clinic Location'),
        ),
    ]
