# Generated by Django 5.2.3 on 2025-09-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0020_ratedappsettings_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedappsettings',
            name='additional_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Configuration'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='auth_type',
            field=models.CharField(choices=[('basic', 'Basic Authentication'), ('oauth2', 'OAuth 2.0'), ('api_key', 'API Key')], default='basic', max_length=20, verbose_name='Authentication Type'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='base_url',
            field=models.URLField(default='https://api.au1.cliniko.com/v1/', max_length=300, verbose_name='API Base URL'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='software_type',
            field=models.CharField(choices=[('cliniko', 'Cliniko'), ('pracsuite', 'PracSuite')], default='cliniko', max_length=50, verbose_name='Software Type'),
        ),
    ]
