# Generated by Django 5.2.3 on 2025-09-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0021_ratedappsettings_additional_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedappsettings',
            name='use_plugin_system',
            field=models.BooleanField(default=False, help_text='Enable new plugin-based integration system'),
        ),
    ]
