# Generated by Django 5.2.3 on 2025-09-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0022_ratedappsettings_use_plugin_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedappsettings',
            name='use_plugin_system',
        ),
    ]
