# Generated by Django 5.2.3 on 2025-09-23 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0023_remove_ratedappsettings_use_plugin_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedappsettings',
            name='analytics_enabled',
            field=models.BooleanField(default=False, help_text='Whether analytics processing is enabled'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='analytics_preset',
            field=models.ForeignKey(blank=True, help_text='Active preset for analytics processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_settings', to='patient_rating.scoringconfiguration'),
        ),
        migrations.CreateModel(
            name='AnalyticsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(choices=[('3', 'Last 3 months'), ('6', 'Last 6 months'), ('12', 'Last 12 months'), ('24', 'Last 24 months')], help_text='Date range for patient selection', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('scheduled_time', models.TimeField(help_text='Time to run the job (in clinic timezone)')),
                ('scheduled_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly jobs', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Analysing...'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial Completion')], default='pending', max_length=20)),
                ('last_run_started', models.DateTimeField(blank=True, null=True)),
                ('last_run_completed', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('patients_processed', models.IntegerField(default=0)),
                ('patients_failed', models.IntegerField(default=0)),
                ('processed_patient_ids', models.JSONField(blank=True, default=list, help_text='List of successfully processed patient IDs')),
                ('failed_patient_ids', models.JSONField(blank=True, default=list, help_text='List of failed patient IDs with error messages')),
                ('error_log', models.TextField(blank=True, help_text='Detailed error messages')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset', models.ForeignKey(help_text='Scoring configuration used for analysis', on_delete=django.db.models.deletion.PROTECT, related_name='analytics_jobs', to='patient_rating.scoringconfiguration')),
            ],
            options={
                'verbose_name': 'Analytics Job',
                'verbose_name_plural': 'Analytics Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='analytics_last_job',
            field=models.ForeignKey(blank=True, help_text='Reference to the current/last analytics job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patient_rating.analyticsjob'),
        ),
    ]
