# Generated by Django 5.2.3 on 2025-09-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0024_ratedappsettings_analytics_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringconfiguration',
            name='is_active',
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='is_active_for_analytics',
            field=models.BooleanField(default=False, help_text='Active configuration for analytics'),
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='is_active_for_scoring',
            field=models.BooleanField(default=False, help_text='Active configuration for scoring'),
        ),
        migrations.AlterField(
            model_name='analyticsjob',
            name='date_range',
            field=models.CharField(choices=[('1d', '1 day'), ('3', '3 months'), ('6', '6 months'), ('1y', '1 year'), ('2y', '2 years'), ('5y', '5 years'), ('10y', '10 years')], help_text='Date range for patient selection', max_length=10),
        ),
    ]
