# Generated by Django 5.2.3 on 2025-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0025_remove_scoringconfiguration_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behaviorcategory',
            old_name='is_active',
            new_name='is_active_for_scoring',
        ),
        migrations.RemoveField(
            model_name='scoringconfiguration',
            name='is_active_for_scoring',
        ),
        migrations.AddField(
            model_name='behaviorcategory',
            name='is_active_for_analytics',
            field=models.BooleanField(default=True, help_text='Active for analytics processing'),
        ),
        migrations.AddField(
            model_name='scoringconfiguration',
            name='is_active_for_behavior',
            field=models.BooleanField(default=False, help_text='Active preset for patient behavior scoring'),
        ),
        migrations.AlterField(
            model_name='scoringconfiguration',
            name='is_active_for_analytics',
            field=models.BooleanField(default=False, help_text='Active preset for analytics processing'),
        ),
    ]
