# Generated by Django 5.2.3 on 2025-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0026_rename_is_active_behaviorcategory_is_active_for_scoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedappsettings',
            name='clinic_email',
            field=models.EmailField(blank=True, help_text='Email address for analytics reports', max_length=254, null=True, verbose_name='Clinic Email'),
        ),
    ]
