# Generated by Django 5.2.3 on 2025-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0028_analyticsjob_is_test_mode_analyticsjob_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedappsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Password'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
        migrations.AddField(
            model_name='ratedappsettings',
            name='smtp_username',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SMTP Username'),
        ),
    ]
