# Generated by Django 5.2.3 on 2025-07-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0007_scoringconfiguration_points_per_consecutive_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='likability',
            field=models.IntegerField(default=0, help_text='Manual likability score (0-100)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='unlikability',
            field=models.IntegerField(default=0, help_text='Manual unlikability score (0-100)'),
        ),
    ]
