# Generated by Django 5.2.3 on 2025-08-12 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_rating', '0013_alter_scoringconfiguration_points_per_cancellation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='unlikability',
        ),
        migrations.AlterField(
            model_name='patient',
            name='likability',
            field=models.IntegerField(default=0, help_text='Patient likability score from -100 (very unlikable) to +100 (very likable)', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
